### ISSUE TITLE
404 not found when trying to send a Follow to Threads

### ISSUE THREAD

**Issue by mattes3** [fedify-dev/fedify#125]
I guess I need a little help here. My app is unable to send a Follow activity to an actor on Threads.

The thing is that Fedify inside my app does several webfinger calls on the actor on Threads (one is OK, one returns 404), but it looks the actor up correctly, and successfully discovers the inbox URL.

Then, Threads says "404 not found" when I actually try to post the `Follow` activity to the actor's personal inbox, using `sendActivity`.

Mastodon is able to follow the same actor, and when I try `fedify inbox -f @newsmast@threads.net`, it also says: `✔ Sent follow request to @newsmast@threads.net`. So if both of these things work, there must be something special in the way I use Fedify in my app. 🤔 

Here are the log messages. Can you spot the root cause of why it does not work?

```
08:46:50.463 DBG fedify·webfinger·lookup Fetching WebFinger resource descriptor from 'https://threads.net/.well-known/webfinger?resource=acct%3Anewsmast%40threads.net'...
(node:37344) ExperimentalWarning: The Ed25519 Web Crypto API algorithm is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
08:46:50.729 DBG fedify·runtime·docloader Fetching document: 'GET' 'https://threads.net/ap/users/17841465837815305/' {
  accept: 'application/activity+json, application/ld+json',
  date: 'Thu, 29 Aug 2024 08:46:50 GMT',
  host: 'threads.net',
  signature: 'keyId="https://localtunnel.bohlenlabs.com/ap/actor/matthias#main-key",algorithm="rsa-sha256",headers="(request-target) accept date host",signature="QlM9yX2V0Gck51W9IfIPQbCx1AadgvXJo/rN1bBLwvc7h5F8Umxii/VklxGR+DN3SbRwItbEjbUczd6ERgrJCMbY7gYm0xm/ZWWQXovLBdO4uAGNEkfO4yu4YEUS8KeD1c0IfhcT4X09Z771ENb2i1C33xsuj1L4d7Yf/yN3aS7MkZpiNiKyBhsmEyeS+6z6xXN9MNOLht4/tL9HbhPmyhqa11lO2r5I9C35deqHdWj8rZu6N29P5mbyRdVafd3Ty3jzp+sJtgh47uIvGhMyFPqaq2kRwGfHE9/LJiXDYyo53M5pfVQ9DJ6G6ZVUcOd5shzmH6KdYEltMoCYCm+t12zDM4Rt2yFHW6snpMXaZ0VO3rYGmwRC2e2SLZ3TKBVJceeZGd3kp1sE/T5ufhOqxB2ZFnKTpbj8vGZcer9YcSnNw+9NxFKe2medq2tWbZc1tRWfh0+lJ6Y5Qcm7feTpDjbZD5BqXyJ13ZAFq/UpjbXKzbUdnr1Fqa0hWZVBFcFlc8/GMhWBmCCSuRfWO8JSNrAd1vkrYFI92e/Z9Z0DcJ1gawZIfD7DyAjx+IP0S/TJ0JJ1GnMxYDD7vBKuD0/5uRGA+y+dEHkvnJSDqSCVckwAqPxUUKICpOF02OL2lrcdlbfpm85vcnYD/MYVqfUQ0z3zorI3qnpdtfxnSV0g8GU="'
}
incoming call to Fedify middleware {
  host: 'localtunnel.bohlenlabs.com',
  'user-agent': 'facebookexternalua',
  accept: 'application/ld+json; profile="https://www.w3.org/ns/activitystreams"',
  'accept-encoding': 'deflate, gzip',
  date: 'Thu, 29 Aug 2024 08:46:51 GMT',
  signature: 'keyId="https://threads.net/ap/users/threads.sys/#main-key",algorithm="rsa-sha256",headers="(request-target) host date",signature="VtqKk+wdev6YEDbcWbpIn32YQLNjDSaqBrLTha1q73CPqTqjpWBeRk5U4BFc9LHBzgqYk3XsNISwZbuaueGXlHY2LIQz4qzmScINPdiiO79J9GEz+YegGBSaXtdfygJvGjbeZnuXYaahFZ+ZQ2zxuHx3iOMRQdq8hTOs/39WCucv3quPxn7RaNzqHqRXCuPLm6wwvLIeVyiWEMVUoRd6HbNHNACtcWItH2o7cms0q+aTFTnjvt+5HcvTEU7BoXN8p1HiM6x6h5wqPNxI5hK2gzzLet8MblkwX9Dj8TTWFjPp/qxEuEZ2YKROB680bNRfM78p0m2nHH9nkE+HGha+iw=="',
  'x-forwarded-for': '69.171.249.15',
  'x-forwarded-host': 'localtunnel.bohlenlabs.com',
  'x-forwarded-proto': 'https',
  traceparent: '00-07e2f927c06a408e31b081ecfa486e17-14eacdd6808e86d5-01'
}
08:46:51.460 DBG fedify·runtime·docloader Using preloaded context: 'https://w3id.org/security/multikey/v1'.
08:46:51.520 DBG fedify·runtime·docloader Using preloaded context: 'https://w3id.org/security/v1'.
08:46:51.585 DBG fedify·runtime·docloader Using preloaded context: 'https://www.w3.org/ns/activitystreams'.
08:46:51.631 DBG fedify·runtime·docloader Using preloaded context: 'https://w3id.org/security/data-integrity/v1'.
08:46:51.682 DBG fedify·runtime·docloader Using preloaded context: 'https://www.w3.org/ns/did/v1'.
08:46:51.722 INF fedify·federation·http 'GET' '/ap/actor/matthias': 200
[2024-08-29T08:46:51.727Z] ACCESS 69.171.249.15 GET /ap/actor/matthias  200  344.495 ms - -
08:46:51.918 DBG fedify·runtime·docloader Fetched document: 200 'https://threads.net/ap/users/17841465837815305/' {
  'alt-svc': 'h3=":443"; ma=86400',
  'cache-control': 'private, no-cache, no-store, must-revalidate',
  connection: 'keep-alive',
  'content-encoding': 'br',
  'content-type': 'application/activity+json; charset=utf-8',
  date: 'Thu, 29 Aug 2024 08:46:51 GMT',
  expires: 'Sat, 01 Jan 2000 00:00:00 GMT',
  pragma: 'no-cache',
  'strict-transport-security': 'max-age=31536000; preload; includeSubDomains',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  'x-fb-debug': 'FzPX5wb5630oBcc+kgqToQ0F6WBPlWdgWQDXys+1jFha5ZzAgljwqL01S20KiufcGeQOjtGReggjBn6wJF9+fg==',
  'x-fb-request-id': 'A6vLUHOT1lUmBJnnQiy6YGv',
  'x-fb-rev': '1016066716',
  'x-fb-server-load': '49',
  'x-fb-trace-id': 'AQt+JFKUfTX',
  'x-stack': 'www'
}
08:46:51.921 DBG fedify·runtime·docloader Using preloaded context: 'https://www.w3.org/ns/activitystreams'.
08:46:51.922 DBG fedify·runtime·docloader Using preloaded context: 'https://w3id.org/security/v1'.
08:46:51.923 DBG fedify·runtime·docloader Using preloaded context: 'https://www.w3.org/ns/activitystreams'.
08:46:51.923 DBG fedify·runtime·docloader Using preloaded context: 'https://w3id.org/security/v1'.
08:46:51.929 DBG fedify·webfinger·lookup Fetching WebFinger resource descriptor from 'https://threads.net/.well-known/webfinger?resource=https%3A%2F%2Fthreads.net%2Fap%2Fusers%2F17841465837815305%2F'...
08:46:52.087 DBG fedify·webfinger·lookup Failed to fetch WebFinger resource descriptor: 404 'Not Found'.
sending follow Follow {
  id: URL 'https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/',
  actor: URL 'https://localtunnel.bohlenlabs.com/ap/actor/matthias',
  object: URL 'https://threads.net/ap/users/17841465837815305/'
}
08:46:52.124 DBG fedify·federation·outbox Sending activity 'https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/' to inboxes:
[
  'https://threads.net/ap/users/17841465837815305/inbox/',
  [length]: 1
]
08:46:52.125 DBG fedify·federation·outbox Enqueuing activity 'https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/' to send later.
[2024-08-29T08:46:52.133Z] ACCESS 91.5.108.45 POST /social/external/follow/newsmast@threads.net  200  1837.393 ms - 300
08:46:52.418 ERR fedify·federation·outbox Failed to send activity 'https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/' to 'https://threads.net/ap/users/17841465837815305/inbox/' (404 'Not Found'):
'{"success":false,"error":"Not found"}'
08:46:52.419 ERR fedify·federation·outbox Failed to send activity 'https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/' to 'https://threads.net/ap/users/17841465837815305/inbox/' (attempt #0); retry...:
Error: Failed to send activity https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/ to https://threads.net/ap/users/17841465837815305/inbox/ (404 Not Found):
{"success":false,"error":"Not found"}
    at sendActivity (file:///Users/bohlenma/Programming/heroku/eliza/eliza.money/node_modules/@fedify/fedify/esm/federation/send.js:117:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #listenOutboxMessage (file:///Users/bohlenma/Programming/heroku/eliza/eliza.money/node_modules/@fedify/fedify/esm/federation/middleware.js:139:13)
    at async #listenQueue (file:///Users/bohlenma/Programming/heroku/eliza/eliza.money/node_modules/@fedify/fedify/esm/federation/middleware.js:102:13) {
  [stack]: 'Error: Failed to send activity https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/ to https://threads.net/ap/users/17841465837815305/inbox/ (404 Not Found):\n' +
    '{"success":false,"error":"Not found"}\n' +
    '    at sendActivity (file:///Users/bohlenma/Programming/heroku/eliza/eliza.money/node_modules/@fedify/fedify/esm/federation/send.js:117:15)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async #listenOutboxMessage (file:///Users/bohlenma/Programming/heroku/eliza/eliza.money/node_modules/@fedify/fedify/esm/federation/middleware.js:139:13)\n' +
    '    at async #listenQueue (file:///Users/bohlenma/Programming/heroku/eliza/eliza.money/node_modules/@fedify/fedify/esm/federation/middleware.js:102:13)',
  [message]: 'Failed to send activity https://localtunnel.bohlenlabs.com/ap/actor/matthias#follows/https://threads.net/ap/users/17841465837815305/ to https://threads.net/ap/users/17841465837815305/inbox/ (404 Not Found):\n' +
    '{"success":false,"error":"Not found"}'
}
```

**Comment by dahlia** [comment]
It's difficult for me to find the cause just by looking at the logs, can you show me the code?

**Comment by mattes3** [comment]
It's pretty standard:

```typescript
const ctx = federation.createContext(req, contextData);
const senderHandle = sender.username;
const actorUri = ctx.getActorUri(senderHandle);

const createActivity = toCreate({
    actorUri,
    tos: [PUBLIC_COLLECTION],
    ccs: [ctx.getFollowersUri(senderHandle)],
    comment,
});

await ctx.sendActivity({ handle: senderHandle }, 'followers', createActivity, {
    preferSharedInbox: true,
});
```

Works with Mastodon but not with Threads.

**Comment by dahlia** [comment]
Your code looks like it's sending a `Create` activity, not `Follow`?

**Comment by mattes3** [comment]
`lookupObject` succeeds, but `sendActivity` fails.

**Comment by dahlia** [comment]
Hmmm… I'm sorry, but I'm clueless just looking at those logs. 😅

**Comment by mattes3** [comment]
Hmmm... I tried this with activitypub.academy which is hosted in Germany. It works, so my theory must be wrong.

<img width="927" alt="CleanShot 2024-08-29 at 15 57 44@2x" src="https://github.com/user-attachments/assets/990a1e9d-d421-45a2-9f16-d7fca4b44a50">

**Comment by dahlia** [comment]
> Could you check if you really get an Accept when you do a `fedify inbox -f @newsmast@threads.net`?

Oh, I got a `404 Not Found` too:

```
error: Uncaught (in promise) Error: Failed to send activity https://53e21fa6b244e8.lhr.life/i#follows/https://threads.net/ap/users/17841465837815305/ to https://threads.net/ap/users/17841465837815305/inbox/ (404 Not Found):
{"success":false,"error":"Not found"}
    throw new Error(
          ^
    at sendActivity (file:///home/dahlia/Projects/dahlia/fedify/src/federation/send.ts:224:11)
    at eventLoopTick (ext:core/01_core.js:174:7)
    at async Promise.all (index 0)
    at async FederationImpl.sendActivity (file:///home/dahlia/Projects/dahlia/fedify/src/federation/middleware.ts:1934:7)
    at async ContextImpl.sendActivity (file:///home/dahlia/Projects/dahlia/fedify/src/federation/middleware.ts:2538:12)
    at async Command.actionHandler (file:///home/dahlia/Projects/dahlia/fedify/cli/inbox.tsx:96:9)
    at async Command.execute (https://jsr.io/@cliffy/command/1.0.0-rc.4/command.ts:1937:7)
    at async Command.parseCommand (https://jsr.io/@cliffy/command/1.0.0-rc.4/command.ts:1769:14)
    at async file:///home/dahlia/Projects/dahlia/fedify/cli/mod.ts:55:3
```

**Comment by mattes3** [comment]
Ah, in that case, you “only” need to find out why Mastodon can follow them and Fedify can’t. Pretty weird behavior of Threads.

**Comment by dahlia** [comment]
Cause found. Threads fail to verify a signature if the `SHA-256=` part of the `Digest` header is written in lowercase. I'm fixing it!

**Comment by dahlia** [comment]
[Fixed in 0.14.2 & 0.13.3.](https://hollo.social/@fedify/0191a184-d93b-760c-a0e9-44fa69f58d87)

**Comment by mattes3** [comment]
Oh my goodness, how did you figure this out? Genius!

**Comment by mattes3** [comment]
Now I am using 0.14.2. There is still one error in the log but it does not seem to be fatal:

```
07:08:41.018 DBG fedify·webfinger·lookup Fetching WebFinger resource descriptor from 'https://threads.net/.well-known/webfinger?resource=https%3A%2F%2Fthreads.net%2Fap%2Fusers%2F17841465837815305%2F'...
07:08:41.189 DBG fedify·webfinger·lookup Failed to fetch WebFinger resource descriptor: 404 'Not Found'.
```

I don't know why Fedify generates this query because I gave it the `acct:...` notation, not the document URL notation when I called `lookupObject()`.

**Comment by mattes3** [comment]
One learning: When I sent  Undo/Follow activity, Threads crashed with status 500. I found out that this was bad:

```typescript
const undoActivity = new Undo({
    actor: new URL(follower.iri),
    object: new URL(affectedFollow.iri),,
});
```

Instead, this here worked:

```typescript
const undoActivity = new Undo({
    actor: new URL(follower.iri),
    object: new Follow({
        id: new URL(affectedFollow.iri),
        actor: new URL(affectedFollow.followerIRI),
        object: new URL(affectedFollow.followingIRI),
    }),
});
```
